# Generated by Django 5.2 on 2025-04-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('menu_name', models.CharField(help_text='The name of the menu this item belongs to', max_length=100, verbose_name='menu name')),
                ('url', models.CharField(blank=True, help_text='URL or named URL pattern', max_length=255, verbose_name='url')),
                ('named_url', models.CharField(blank=True, help_text='Named URL pattern', max_length=100, verbose_name='named url')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['order'],
            },
        ),
    ]
