# Generated by Django 5.2 on 2025-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(help_text='Название меню, к которому принаджележит пункт', max_length=100, verbose_name='menu name'),
        ),
    ]
