# Generated by Django 5.2 on 2025-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_expanded',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
